/*
 * Buttons List Action Types
 */


// *** button *** //

export const SET_BUTTON_TEXT = 'SET_BUTTON_TEXT';
export const SET_BUTTON_CLASS = 'SET_BUTTON_CLASS';

// *** buttons api *** //

export const GET_BUTTONS_REQUEST = 'GET_BUTTONS_REQUEST';
export const GET_BUTTONS_FAILURE = 'GET_BUTTONS_FAILURE';
export const GET_BUTTONS_SUCCESS = 'GET_BUTTONS_SUCCESS';

export const GET_BUTTON_REQUEST = 'GET_BUTTON_REQUEST';
export const GET_BUTTON_FAILURE = 'GET_BUTTON_FAILURE';
export const GET_BUTTON_SUCCESS = 'GET_BUTTON_SUCCESS';

export const ADD_BUTTON_REQUEST = 'ADD_BUTTON_REQUEST';
export const ADD_BUTTON_FAILURE = 'ADD_BUTTON_FAILURE';
export const ADD_BUTTON_SUCCESS = 'ADD_BUTTON_SUCCESS';

export const EDIT_BUTTON_REQUEST = 'EDIT_BUTTON_REQUEST';
export const EDIT_BUTTON_FAILURE = 'EDIT_BUTTON_FAILURE';
export const EDIT_BUTTON_SUCCESS = 'EDIT_BUTTON_SUCCESS';

export const DELETE_BUTTON_REQUEST = 'DELETE_BUTTON_REQUEST';
export const DELETE_BUTTON_FAILURE = 'DELETE_BUTTON_FAILURE';
export const DELETE_BUTTON_SUCCESS = 'DELETE_BUTTON_SUCCESS';

