/*
 * Text Style Actions Types
 */


// *** fonts *** //

export const SET_FONT = 'SET_FONT';
export const SET_FONT_SIZE = 'SET_FONT_SIZE';
export const SET_FONT_STYLE = 'SET_FONT_STYLE';
export const SET_FONT_WEIGHT = 'SET_FONT_WEIGHT';
export const SET_TEXT_TRANSFORM = 'SET_TEXT_TRANSFORM';
export const SET_TEXT_DECORATION = 'SET_TEXT_DECORATION';
export const SET_TEXT_COLOR = 'SET_TEXT_COLOR';
export const SET_TEXT_ALIGN = 'SET_TEXT_ALIGN';

// *** shadows *** //

export const ADD_TEXT_SHADOW = 'ADD_TEXT_SHADOW';
export const DELETE_TEXT_SHADOW = 'DELETE_TEXT_SHADOW';

export const SET_TEXT_SHADOW_DEFAULT = 'SET_TEXT_SHADOW_DEFAULT';
export const SET_TEXT_SHADOW_SHIFT_X = 'SET_TEXT_SHADOW_SHIFT_X';
export const SET_TEXT_SHADOW_SHIFT_Y = 'SET_TEXT_SHADOW_SHIFT_Y';
export const SET_TEXT_SHADOW_BLUR = 'SET_TEXT_SHADOW_BLUR';
export const SET_TEXT_SHADOW_COLOR = 'SET_TEXT_SHADOW_COLOR';


/*
 * Size Style Actions Types
 */


// *** size *** //

export const SET_WIDTH = 'SET_WIDTH';
export const SET_HEIGHT = 'SET_HEIGHT';

// *** margin *** //

export const SET_MARGIN_TOP = 'SET_MARGIN_TOP';
export const SET_MARGIN_RIGHT = 'SET_MARGIN_RIGHT';
export const SET_MARGIN_BOTTOM = 'SET_MARGIN_BOTTOM';
export const SET_MARGIN_LEFT = 'SET_MARGIN_LEFT';

// *** padding *** //

export const SET_PADDING_TOP = 'SET_PADDING_TOP';
export const SET_PADDING_RIGHT = 'SET_PADDING_RIGHT';
export const SET_PADDING_BOTTOM = 'SET_PADDING_BOTTOM';
export const SET_PADDING_LEFT = 'SET_PADDING_LEFT';

// *** transform *** //

export const SET_TRANSFORM_ORIGIN_X = 'SET_TRANSFORM_ORIGIN_X';
export const SET_TRANSFORM_ORIGIN_Y = 'SET_TRANSFORM_ORIGIN_Y';
export const SET_TRANSFORM_SCALE_X = 'SET_TRANSFORM_SCALE_X';
export const SET_TRANSFORM_SCALE_Y = 'SET_TRANSFORM_SCALE_Y';
export const SET_TRANSFORM_SKEW_X = 'SET_TRANSFORM_SKEW_X';
export const SET_TRANSFORM_SKEW_Y = 'SET_TRANSFORM_SKEW_Y';
export const SET_TRANSFORM_TRANSLATE_X = 'SET_TRANSFORM_TRANSLATE_X';
export const SET_TRANSFORM_TRANSLATE_Y = 'SET_TRANSFORM_TRANSLATE_Y';
export const SET_TRANSFORM_ROTATE = 'SET_TRANSFORM_ROTATE';


/*
 * Background Style Actions Types
 */


// *** background *** //

export const SET_BTN_COLOR = 'SET_BTN_COLOR';
export const SET_BTN_OPACITY = 'SET_BTN_OPACITY';

// *** border *** //

export const SET_BORDER_WIDTH = 'SET_BORDER_WIDTH';
export const SET_BORDER_STYLE = 'SET_BORDER_STYLE';
export const SET_BORDER_COLOR = 'SET_BORDER_COLOR';

export const SET_BORDER_TOP_WIDTH = 'SET_BORDER_TOP_WIDTH';
export const SET_BORDER_TOP_STYLE = 'SET_BORDER_TOP_STYLE';
export const SET_BORDER_TOP_COLOR = 'SET_BORDER_TOP_COLOR';

export const SET_BORDER_RIGHT_WIDTH = 'SET_BORDER_RIGHT_WIDTH';
export const SET_BORDER_RIGHT_STYLE = 'SET_BORDER_RIGHT_STYLE';
export const SET_BORDER_RIGHT_COLOR = 'SET_BORDER_RIGHT_COLOR';

export const SET_BORDER_BOTTOM_WIDTH = 'SET_BORDER_BOTTOM_WIDTH';
export const SET_BORDER_BOTTOM_STYLE = 'SET_BORDER_BOTTOM_STYLE';
export const SET_BORDER_BOTTOM_COLOR = 'SET_BORDER_BOTTOM_COLOR';

export const SET_BORDER_LEFT_WIDTH = 'SET_BORDER_LEFT_WIDTH';
export const SET_BORDER_LEFT_STYLE = 'SET_BORDER_LEFT_STYLE';
export const SET_BORDER_LEFT_COLOR = 'SET_BORDER_LEFT_COLOR';

export const SET_BORDER_RADIUS = 'SET_BORDER_RADIUS';
export const SET_BORDER_TOP_LEFT_RADIUS = 'SET_BORDER_TOP_LEFT_RADIUS';
export const SET_BORDER_TOP_RIGHT_RADIUS = 'SET_BORDER_TOP_LEFT_RADIUS';
export const SET_BORDER_BOTTOM_LEFT_RADIUS = 'SET_BORDER_BOTTOM_LEFT_RADIUS';
export const SET_BORDER_BOTTOM_RIGHT_RADIUS = 'SET_BORDER_BOTTOM_RIGHT_RADIUS';

// *** shadow *** //

export const ADD_SHADOW = 'ADD_SHADOW';
export const DELETE_SHADOW = 'DELETE_SHADOW';

export const SET_SHADOW_DEFAULT = 'SET_SHADOW_DEFAULT';
export const SET_SHADOW_INSET = 'SET_SHADOW_INSET';
export const SET_SHADOW_SHIFT_X = 'SET_SHADOW_SHIFT_X';
export const SET_SHADOW_SHIFT_Y = 'SET_SHADOW_SHIFT_Y';
export const SET_SHADOW_BLUR = 'SET_SHADOW_BLUR';
export const SET_SHADOW_STRETCHING = 'SET_SHADOW_STRETCHING';
export const SET_SHADOW_COLOR = 'SET_SHADOW_COLOR';


/*
 * Transition Style Actions Types
 */

// *** transition *** //

export const SET_TRANSITION_PROPERTY = 'SET_TRANSITION_PROPERTY';
export const SET_TRANSITION_TIMING_FUNCTION = 'SET_TRANSITION_TIMING_FUNCTION';
export const SET_TRANSITION_DURATION = 'SET_TRANSITION_DURATION';
export const SET_TRANSITION_DELAY = 'SET_TRANSITION_DELAY';
