/*
 * Text Style Active Actions Types
 */


// *** fonts *** //

export const SET_FONT_SIZE = 'SET_FONT_SIZE:ACTIVE';
export const SET_FONT_WEIGHT = 'SET_FONT_WEIGHT:ACTIVE';
export const SET_TEXT_TRANSFORM = 'SET_TEXT_TRANSFORM:ACTIVE';
export const SET_TEXT_DECORATION = 'SET_TEXT_DECORATION:ACTIVE';
export const SET_TEXT_COLOR = 'SET_TEXT_COLOR:ACTIVE';

// *** shadows *** //

export const ADD_TEXT_SHADOW = 'ADD_TEXT_SHADOW:ACTIVE';
export const DELETE_TEXT_SHADOW = 'DELETE_TEXT_SHADOW:ACTIVE';

export const SET_TEXT_SHADOW_DEFAULT = 'SET_TEXT_SHADOW_DEFAULT:ACTIVE';
export const SET_TEXT_SHADOW_SHIFT_X = 'SET_TEXT_SHADOW_SHIFT_X:ACTIVE';
export const SET_TEXT_SHADOW_SHIFT_Y = 'SET_TEXT_SHADOW_SHIFT_Y:ACTIVE';
export const SET_TEXT_SHADOW_BLUR = 'SET_TEXT_SHADOW_BLUR:ACTIVE';
export const SET_TEXT_SHADOW_COLOR = 'SET_TEXT_SHADOW_COLOR:ACTIVE';


/*
 * Size Style Active Actions Types
 */


// *** size *** //

export const SET_WIDTH = 'SET_WIDTH:ACTIVE';
export const SET_HEIGHT = 'SET_HEIGHT:ACTIVE';

// *** margin *** //

export const SET_MARGIN_TOP = 'SET_MARGIN_TOP:ACTIVE';
export const SET_MARGIN_RIGHT = 'SET_MARGIN_RIGHT:ACTIVE';
export const SET_MARGIN_BOTTOM = 'SET_MARGIN_BOTTOM:ACTIVE';
export const SET_MARGIN_LEFT = 'SET_MARGIN_LEFT:ACTIVE';

// *** padding *** //

export const SET_PADDING_TOP = 'SET_PADDING_TOP:ACTIVE';
export const SET_PADDING_RIGHT = 'SET_PADDING_RIGHT:ACTIVE';
export const SET_PADDING_BOTTOM = 'SET_PADDING_BOTTOM:ACTIVE';
export const SET_PADDING_LEFT = 'SET_PADDING_LEFT:ACTIVE';

// *** transform *** //

export const SET_TRANSFORM_ORIGIN_X = 'SET_TRANSFORM_ORIGIN_X:ACTIVE';
export const SET_TRANSFORM_ORIGIN_Y = 'SET_TRANSFORM_ORIGIN_Y:ACTIVE';
export const SET_TRANSFORM_SCALE_X = 'SET_TRANSFORM_SCALE_X:ACTIVE';
export const SET_TRANSFORM_SCALE_Y = 'SET_TRANSFORM_SCALE_Y:ACTIVE';
export const SET_TRANSFORM_SKEW_X = 'SET_TRANSFORM_SKEW_X:ACTIVE';
export const SET_TRANSFORM_SKEW_Y = 'SET_TRANSFORM_SKEW_Y:ACTIVE';
export const SET_TRANSFORM_TRANSLATE_X = 'SET_TRANSFORM_TRANSLATE_X:ACTIVE';
export const SET_TRANSFORM_TRANSLATE_Y = 'SET_TRANSFORM_TRANSLATE_Y:ACTIVE';
export const SET_TRANSFORM_ROTATE = 'SET_TRANSFORM_ROTATE:ACTIVE';


/*
 * Background Style Active Actions Types
 */


// *** background *** //

export const SET_BTN_COLOR = 'SET_BTN_COLOR:ACTIVE';
export const SET_BTN_OPACITY = 'SET_BTN_OPACITY:ACTIVE';

// *** border *** //

export const SET_BORDER_WIDTH = 'SET_BORDER_WIDTH:ACTIVE';
export const SET_BORDER_STYLE = 'SET_BORDER_STYLE:ACTIVE';
export const SET_BORDER_COLOR = 'SET_BORDER_COLOR:ACTIVE';

export const SET_BORDER_TOP_WIDTH = 'SET_BORDER_TOP_WIDTH:ACTIVE';
export const SET_BORDER_TOP_STYLE = 'SET_BORDER_TOP_STYLE:ACTIVE';
export const SET_BORDER_TOP_COLOR = 'SET_BORDER_TOP_COLOR:ACTIVE';

export const SET_BORDER_RIGHT_WIDTH = 'SET_BORDER_RIGHT_WIDTH:ACTIVE';
export const SET_BORDER_RIGHT_STYLE = 'SET_BORDER_RIGHT_STYLE:ACTIVE';
export const SET_BORDER_RIGHT_COLOR = 'SET_BORDER_RIGHT_COLOR:ACTIVE';

export const SET_BORDER_BOTTOM_WIDTH = 'SET_BORDER_BOTTOM_WIDTH:ACTIVE';
export const SET_BORDER_BOTTOM_STYLE = 'SET_BORDER_BOTTOM_STYLE:ACTIVE';
export const SET_BORDER_BOTTOM_COLOR = 'SET_BORDER_BOTTOM_COLOR:ACTIVE';

export const SET_BORDER_LEFT_WIDTH = 'SET_BORDER_LEFT_WIDTH:ACTIVE';
export const SET_BORDER_LEFT_STYLE = 'SET_BORDER_LEFT_STYLE:ACTIVE';
export const SET_BORDER_LEFT_COLOR = 'SET_BORDER_LEFT_COLOR:ACTIVE';

export const SET_BORDER_RADIUS = 'SET_BORDER_RADIUS:ACTIVE';
export const SET_BORDER_TOP_LEFT_RADIUS = 'SET_BORDER_TOP_LEFT_RADIUS:ACTIVE';
export const SET_BORDER_TOP_RIGHT_RADIUS = 'SET_BORDER_TOP_LEFT_RADIUS:ACTIVE';
export const SET_BORDER_BOTTOM_LEFT_RADIUS = 'SET_BORDER_BOTTOM_LEFT_RADIUS:ACTIVE';
export const SET_BORDER_BOTTOM_RIGHT_RADIUS = 'SET_BORDER_BOTTOM_RIGHT_RADIUS:ACTIVE';

// *** shadow *** //

export const ADD_SHADOW = 'ADD_SHADOW:ACTIVE';
export const DELETE_SHADOW = 'DELETE_SHADOW:ACTIVE';

export const SET_SHADOW_DEFAULT = 'SET_SHADOW_DEFAULT:ACTIVE';
export const SET_SHADOW_INSET = 'SET_SHADOW_INSET:ACTIVE';
export const SET_SHADOW_SHIFT_X = 'SET_SHADOW_SHIFT_X:ACTIVE';
export const SET_SHADOW_SHIFT_Y = 'SET_SHADOW_SHIFT_Y:ACTIVE';
export const SET_SHADOW_BLUR = 'SET_SHADOW_BLUR:ACTIVE';
export const SET_SHADOW_STRETCHING = 'SET_SHADOW_STRETCHING:ACTIVE';
export const SET_SHADOW_COLOR = 'SET_SHADOW_COLOR:ACTIVE';

