/*
 * Text Style Hover Actions Types
 */


// *** fonts *** //

export const SET_FONT_SIZE = 'SET_FONT_SIZE:HOVER';
export const SET_FONT_WEIGHT = 'SET_FONT_WEIGHT:HOVER';
export const SET_TEXT_TRANSFORM = 'SET_TEXT_TRANSFORM:HOVER';
export const SET_TEXT_DECORATION = 'SET_TEXT_DECORATION:HOVER';
export const SET_TEXT_COLOR = 'SET_TEXT_COLOR:HOVER';

// *** shadows *** //

export const ADD_TEXT_SHADOW = 'ADD_TEXT_SHADOW:HOVER';
export const DELETE_TEXT_SHADOW = 'DELETE_TEXT_SHADOW:HOVER';

export const SET_TEXT_SHADOW_DEFAULT = 'SET_TEXT_SHADOW_DEFAULT:HOVER';
export const SET_TEXT_SHADOW_SHIFT_X = 'SET_TEXT_SHADOW_SHIFT_X:HOVER';
export const SET_TEXT_SHADOW_SHIFT_Y = 'SET_TEXT_SHADOW_SHIFT_Y:HOVER';
export const SET_TEXT_SHADOW_BLUR = 'SET_TEXT_SHADOW_BLUR:HOVER';
export const SET_TEXT_SHADOW_COLOR = 'SET_TEXT_SHADOW_COLOR:HOVER';


/*
 * Size Style Hover Actions Types
 */


// *** size *** //

export const SET_WIDTH = 'SET_WIDTH:HOVER';
export const SET_HEIGHT = 'SET_HEIGHT:HOVER';

// *** margin *** //

export const SET_MARGIN_TOP = 'SET_MARGIN_TOP:HOVER';
export const SET_MARGIN_RIGHT = 'SET_MARGIN_RIGHT:HOVER';
export const SET_MARGIN_BOTTOM = 'SET_MARGIN_BOTTOM:HOVER';
export const SET_MARGIN_LEFT = 'SET_MARGIN_LEFT:HOVER';

// *** padding *** //

export const SET_PADDING_TOP = 'SET_PADDING_TOP:HOVER';
export const SET_PADDING_RIGHT = 'SET_PADDING_RIGHT:HOVER';
export const SET_PADDING_BOTTOM = 'SET_PADDING_BOTTOM:HOVER';
export const SET_PADDING_LEFT = 'SET_PADDING_LEFT:HOVER';

// *** transform *** //

export const SET_TRANSFORM_ORIGIN_X = 'SET_TRANSFORM_ORIGIN_X:HOVER';
export const SET_TRANSFORM_ORIGIN_Y = 'SET_TRANSFORM_ORIGIN_Y:HOVER';
export const SET_TRANSFORM_SCALE_X = 'SET_TRANSFORM_SCALE_X:HOVER';
export const SET_TRANSFORM_SCALE_Y = 'SET_TRANSFORM_SCALE_Y:HOVER';
export const SET_TRANSFORM_SKEW_X = 'SET_TRANSFORM_SKEW_X:HOVER';
export const SET_TRANSFORM_SKEW_Y = 'SET_TRANSFORM_SKEW_Y:HOVER';
export const SET_TRANSFORM_TRANSLATE_X = 'SET_TRANSFORM_TRANSLATE_X:HOVER';
export const SET_TRANSFORM_TRANSLATE_Y = 'SET_TRANSFORM_TRANSLATE_Y:HOVER';
export const SET_TRANSFORM_ROTATE = 'SET_TRANSFORM_ROTATE:HOVER';


/*
 * Background Style Hover Actions Types
 */


// *** background *** //

export const SET_BTN_COLOR = 'SET_BTN_COLOR:HOVER';
export const SET_BTN_OPACITY = 'SET_BTN_OPACITY:HOVER';

// *** border *** //

export const SET_BORDER_WIDTH = 'SET_BORDER_WIDTH:HOVER';
export const SET_BORDER_STYLE = 'SET_BORDER_STYLE:HOVER';
export const SET_BORDER_COLOR = 'SET_BORDER_COLOR:HOVER';

export const SET_BORDER_TOP_WIDTH = 'SET_BORDER_TOP_WIDTH:HOVER';
export const SET_BORDER_TOP_STYLE = 'SET_BORDER_TOP_STYLE:HOVER';
export const SET_BORDER_TOP_COLOR = 'SET_BORDER_TOP_COLOR:HOVER';

export const SET_BORDER_RIGHT_WIDTH = 'SET_BORDER_RIGHT_WIDTH:HOVER';
export const SET_BORDER_RIGHT_STYLE = 'SET_BORDER_RIGHT_STYLE:HOVER';
export const SET_BORDER_RIGHT_COLOR = 'SET_BORDER_RIGHT_COLOR:HOVER';

export const SET_BORDER_BOTTOM_WIDTH = 'SET_BORDER_BOTTOM_WIDTH:HOVER';
export const SET_BORDER_BOTTOM_STYLE = 'SET_BORDER_BOTTOM_STYLE:HOVER';
export const SET_BORDER_BOTTOM_COLOR = 'SET_BORDER_BOTTOM_COLOR:HOVER';

export const SET_BORDER_LEFT_WIDTH = 'SET_BORDER_LEFT_WIDTH:HOVER';
export const SET_BORDER_LEFT_STYLE = 'SET_BORDER_LEFT_STYLE:HOVER';
export const SET_BORDER_LEFT_COLOR = 'SET_BORDER_LEFT_COLOR:HOVER';

export const SET_BORDER_RADIUS = 'SET_BORDER_RADIUS:HOVER';
export const SET_BORDER_TOP_LEFT_RADIUS = 'SET_BORDER_TOP_LEFT_RADIUS:HOVER';
export const SET_BORDER_TOP_RIGHT_RADIUS = 'SET_BORDER_TOP_LEFT_RADIUS:HOVER';
export const SET_BORDER_BOTTOM_LEFT_RADIUS = 'SET_BORDER_BOTTOM_LEFT_RADIUS:HOVER';
export const SET_BORDER_BOTTOM_RIGHT_RADIUS = 'SET_BORDER_BOTTOM_RIGHT_RADIUS:HOVER';

// *** shadow *** //

export const ADD_SHADOW = 'ADD_SHADOW:HOVER';
export const DELETE_SHADOW = 'DELETE_SHADOW:HOVER';

export const SET_SHADOW_DEFAULT = 'SET_SHADOW_DEFAULT:HOVER';
export const SET_SHADOW_INSET = 'SET_SHADOW_INSET:HOVER';
export const SET_SHADOW_SHIFT_X = 'SET_SHADOW_SHIFT_X:HOVER';
export const SET_SHADOW_SHIFT_Y = 'SET_SHADOW_SHIFT_Y:HOVER';
export const SET_SHADOW_BLUR = 'SET_SHADOW_BLUR:HOVER';
export const SET_SHADOW_STRETCHING = 'SET_SHADOW_STRETCHING:HOVER';
export const SET_SHADOW_COLOR = 'SET_SHADOW_COLOR:HOVER';

